### ISSUE TITLE
Component description is prematurely truncated on package summary.

### ISSUE THREAD

**Issue by boughtonp** [markmandel/ColdDoc#4]
What's the rational for doing ListFirst here:
https://github.com/markmandel/ColdDoc/blob/develop/strategy/api/resources/templates/package-summary.html#L55
?

If the aim is to get the first sentence, it needs to be smarter - i.e. exclude any `.` that are not full-stops - probably by looking for one that follows a word character and is followed by whitespace. May or not want to exclude newlines, depending on what the intent is to show.

Another option is to simply show first X words/characters (and append ellipsis to indicate it's been cut).

**Comment by markmandel** [comment]
It was a quick and easy way to get at the first sentence without having to get into sentence parsing.

If you think you have a better way to do it, patches are welcome :smile:

**Comment by boughtonp** [comment]
Heh, that's a bit of a sinister looking emoticon...

Anyhow, I'll see if I can send a pull request for it this weekend.

There were a few other things I noticed that could be improved which I'll try and get to too - are you ok with a single generic "cleanup" pull request, or would you prefer individual ones?

**Comment by markmandel** [comment]
Either or, whatever is easier for you.  I need to make some time to fire up my CF VMs and test these out. On face value everything else looks good.

**Comment by markmandel** [comment]
Closing all issues, check out: https://github.com/Ortus-Solutions/DocBox

It's an up to date fork.
