### ISSUE TITLE
Local variable/cfscript error

### ISSUE THREAD

**Issue by robbybankston** [markmandel/ColdDoc#5]
Error:  Local variable localmeta on line 206 must be grouped at the top of the function body. 

In CF8, local variables must come before cfscript tags.

Environment

Server Product  ColdFusion  
Version  8,0,1,195765  
Edition  Enterprise  
Operating System  Windows 2003  
OS Version  5.2  
Adobe Driver Version  3.6 (Build 0017)

**Comment by markmandel** [comment]
Full stack trace please, and what version of ColdDoc.

Seems like an easy bug to fix - want to send through a pull request?

**Comment by robbybankston** [comment]
I adjusted my code locally so it doesn't matter.  I was just alerting you so that if you had any more CF8 users, they wouldn't run into the same issue.  I can also provide the HTML output of the dump if desired.

![cf8 local variable error dump](https://f.cloud.github.com/assets/5431036/1124400/3e56a9aa-1afe-11e3-8331-93d9db5768d8.png)
